Use datacovid19;

LOAD DATA LOCAL INFILE 'C:\Users\Usuario\Documents\Ciclo_4\Practicum 1.2\2doBimestre\CSV/TablaPrincipal.csv' 
INTO TABLE tablaPrincipal FIELDS TERMINATED BY ';' 
ENCLOSED BY '"' LINES TERMINATED BY '\n'; 

load data local infile 'C:\Users\Usuario\Documents\Ciclo_4\Practicum 1.2\2doBimestre\CSV/TablaPrincipal.csv'  
into table datacovid19.variablesprincipales fields terminated by ';' 
enclosed by '"' lines terminated by '\n';


-- MySQL Script generated by MySQL Workbench
-- Thu Jun 17 11:46:41 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema datacovid19
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema datacovid19
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `datacovid19` DEFAULT CHARACTER SET utf8 ;
USE `datacovid19` ;

-- -----------------------------------------------------
-- Table `datacovid19`.`VariablesPrincipales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `datacovid19`.`VariablesPrincipales` (
  `CodigoIsoPais` VARCHAR(15) NOT NULL,
  `Fecha` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Fecha`, `CodigoIsoPais`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `datacovid19`.`Casos Confirmados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `datacovid19`.`Casos Confirmados` (
  `CasosTotales` INT NULL,
  `NuevosCasos` INT NULL,
  `CasosTotalesporMillon` INT NULL,
  `NuevosCasosporMillon` INT NULL,
  `NuevosCasosSuavizadosporMillon` INT NULL,
  `TasadeReproduccion` INT NULL,
  `VariablesPrincipales_Fecha` VARCHAR(45) NOT NULL,
  `VariablesPrincipales_CodigoIsoPais` VARCHAR(5) NOT NULL,
  PRIMARY KEY (`VariablesPrincipales_Fecha`, `VariablesPrincipales_CodigoIsoPais`),
  CONSTRAINT `fk_Casos Confirmados_VariablesPrincipales`
    FOREIGN KEY (`VariablesPrincipales_Fecha` , `VariablesPrincipales_CodigoIsoPais`)
    REFERENCES `mydb`.`VariablesPrincipales` (`Fecha` , `CodigoIsoPais`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `datacovid19`.`Muertes a causa del Covid-19`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `datacovid19`.`Muertes a causa del Covid-19` (
  `MuertesTotales` INT NULL,
  `NuevasMuertes` INT NULL,
  `NuevasMuertesSuavizadas` INT NULL,
  `MuertesTotalesporMillon` INT NULL,
  `NuevasMuertesporMillon` INT NULL,
  `NuevasMuertesSuavizadasporMillon` INT NULL,
  `VariablesPrincipales_Fecha` VARCHAR(45) NOT NULL,
  `VariablesPrincipales_CodigoIsoPais` VARCHAR(5) NOT NULL,
  PRIMARY KEY (`VariablesPrincipales_Fecha`, `VariablesPrincipales_CodigoIsoPais`),
  CONSTRAINT `fk_Muertes a causa del Covid-19_VariablesPrincipales1`
    FOREIGN KEY (`VariablesPrincipales_Fecha` , `VariablesPrincipales_CodigoIsoPais`)
    REFERENCES `mydb`.`VariablesPrincipales` (`Fecha` , `CodigoIsoPais`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `datacovid19`.`Vacunados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `datacovid19`.`Vacunados` (
  `VacunadosTotales` INT NULL,
  `PersonasVacunadas` INT NULL,
  `PersonasCompletamenteVacunadas` INT NULL,
  `NuevasVacunas` INT NULL,
  `NuevasVacunasSuavizadas` INT NULL,
  `VacunasTotalesporCien` INT NULL,
  `PersonasVacunadasporCien` INT NULL,
  `PersonasCompletamenteVacunadasporCien` INT NULL,
  `NuevasVacunasSuavizadasporCien` INT NULL,
  `VariablesPrincipales_Fecha` VARCHAR(45) NOT NULL,
  `VariablesPrincipales_CodigoIsoPais` VARCHAR(5) NOT NULL,
  PRIMARY KEY (`VariablesPrincipales_Fecha`, `VariablesPrincipales_CodigoIsoPais`),
  CONSTRAINT `fk_Vacunados_VariablesPrincipales1`
    FOREIGN KEY (`VariablesPrincipales_Fecha` , `VariablesPrincipales_CodigoIsoPais`)
    REFERENCES `mydb`.`VariablesPrincipales` (`Fecha` , `CodigoIsoPais`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `datacovid19`.`Hospitalizaciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `datacovid19`.`Hospitalizaciones` (
  `PacientesconUCI` INT NOT NULL,
  `PacientesconUCIporMillon` INT NULL,
  `Pacienteshosp` INT NULL,
  `PacienteshospporMillon` INT NULL,
  `Hospitalizacionescol` INT NULL,
  `AdmisionesSemanalesdeUCI` INT NULL,
  `AdmisionesUCIporMillon` INT NULL,
  `AdmisionesHospitalariasSemanales` INT NULL,
  `AdmisionesHospitalariasSemanalesporMillon` INT NULL,
  `VariablesPrincipales_Fecha` VARCHAR(45) NOT NULL,
  `VariablesPrincipales_CodigoIsoPais` VARCHAR(5) NOT NULL,
  PRIMARY KEY (`VariablesPrincipales_Fecha`, `VariablesPrincipales_CodigoIsoPais`),
  CONSTRAINT `fk_Hospitalizaciones_VariablesPrincipales1`
    FOREIGN KEY (`VariablesPrincipales_Fecha` , `VariablesPrincipales_CodigoIsoPais`)
    REFERENCES `mydb`.`VariablesPrincipales` (`Fecha` , `CodigoIsoPais`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `datacovid19`.`Variables Socieconomicas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `datacovid19`.`Variables Socieconomicas` (
  `IndicedeRigurosidad` INT NULL,
  `Poblacion` INT NULL,
  `DensidaddePoblacion` INT NULL,
  `EdadMedia` INT NULL,
  `65aniosMas` INT NULL,
  `70aniosMas` INT NULL,
  `PIBperCapita` INT NULL,
  `PobrezaExtrema` INT NULL,
  `TasadeMortalidadCardiovascular` INT NULL,
  `PrevalenciadeDiabetes` INT NULL,
  `MujeresFumadoras` INT NULL,
  `FumadoresMasculinos` INT NULL,
  `InstalacionesparaLavarselasManos` INT NULL,
  `CamasdeHospotalporMil` INT NULL,
  `EsperanzadeVida` INT NULL,
  `IndicedeDesarrolloHumano` INT NULL,
  `VariablesPrincipales_Fecha` VARCHAR(45) NOT NULL,
  `VariablesPrincipales_CodigoIsoPais` VARCHAR(5) NOT NULL,
  PRIMARY KEY (`VariablesPrincipales_Fecha`, `VariablesPrincipales_CodigoIsoPais`),
  CONSTRAINT `fk_Variables Socieconomicas_VariablesPrincipales1`
    FOREIGN KEY (`VariablesPrincipales_Fecha` , `VariablesPrincipales_CodigoIsoPais`)
    REFERENCES `mydb`.`VariablesPrincipales` (`Fecha` , `CodigoIsoPais`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `datacovid19`.`PruebasRealizadas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `datacovid19`.`PruebasRealizadas` (
  `NuevasPruebas` INT NULL,
  `PruebasTotales` INT NULL,
  `NuevasPruebasporMil` INT NULL,
  `PruebasTotalesporMil` INT NULL,
  `NuevasPruebasSuavizadas` INT NULL,
  `NuevasPruebasSuavizadasporMil` INT NULL,
  `TasaPositiva` VARCHAR(45) NULL,
  `PruebaporCaso` VARCHAR(45) NULL,
  `UnidadesdePrueba` VARCHAR(45) NULL,
  `VariablesPrincipales_Fecha` VARCHAR(45) NOT NULL,
  `VariablesPrincipales_CodigoIsoPais` VARCHAR(5) NOT NULL,
  PRIMARY KEY (`VariablesPrincipales_Fecha`, `VariablesPrincipales_CodigoIsoPais`),
  CONSTRAINT `fk_PruebasRealizadas_VariablesPrincipales1`
    FOREIGN KEY (`VariablesPrincipales_Fecha` , `VariablesPrincipales_CodigoIsoPais`)
    REFERENCES `mydb`.`VariablesPrincipales` (`Fecha` , `CodigoIsoPais`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `datacovid19`.`Empresa_Vacuna_Covid`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `datacovid19`.`Empresa_Vacuna_Covid` (
  `Id_Empresa` VARCHAR(55) NULL,
  `VariablesPrincipales_Fecha` VARCHAR(45) NOT NULL,
  `VariablesPrincipales_CodigoIsoPais` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`VariablesPrincipales_Fecha`, `VariablesPrincipales_CodigoIsoPais`),
  INDEX `fk_Empresa_Vacuna_Covid_VariablesPrincipales1_idx` (`VariablesPrincipales_Fecha` ASC, `VariablesPrincipales_CodigoIsoPais` ASC) VISIBLE,
  CONSTRAINT `fk_Empresa_Vacuna_Covid_VariablesPrincipales1`
    FOREIGN KEY (`VariablesPrincipales_Fecha` , `VariablesPrincipales_CodigoIsoPais`)
    REFERENCES `mydb`.`VariablesPrincipales` (`Fecha` , `CodigoIsoPais`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
